### ISSUE TITLE
Error starting Hop with hop-neo4j in plugins/transforms

### ISSUE THREAD

**Issue by davidlrosenblum** [mattcasters/hop-neo4j#2]
Following error occurs on startup of Hop - the UI never launches

> Error starting the Hop GUI: org.neo4j.hop.ui.model.GraphModelGuiPlugin.getMetastoreElementClass()Ljava/lang/Class;
java.lang.AbstractMethodError: org.neo4j.hop.ui.model.GraphModelGuiPlugin.getMetastoreElementClass()Ljava/lang/Class;
	at org.apache.hop.ui.hopgui.HopGuiEnvironment.initGuiPlugins(HopGuiEnvironment.java:176)
	at org.apache.hop.ui.hopgui.HopGuiEnvironment.init(HopGuiEnvironment.java:73)
	at org.apache.hop.ui.hopgui.HopGuiEnvironment.init(HopGuiEnvironment.java:59)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:291)

Also mis-match in versions 5.0.1 in the zip vs. 5.0.3 listed

**Comment by mattcasters** [comment]
Hi David,

Thanks for testing!  Did you use a very recent build? We're still updating API's all over the place making this really needed.
You can download all builds from:  https://artifactory.project-hop.org/artifactory/hop-snapshots-local/org/hop/hop-assemblies-client/0.20-SNAPSHOT/

**Comment by davidlrosenblum** [comment]
Hi Matt,

Probably my mistake. I am in process of building everything, see if that
helps.  Will look at the link you have here also.

David

On May 2, 2020, at 9:31 AM, Matt Casters <notifications@github.com> wrote:

﻿

Hi David,

Thanks for testing! Did you use a very recent build? We're still updating
API's all over the place making this really needed.
You can download all builds from:
https://artifactory.project-hop.org/artifactory/hop-snapshots-local/org/hop/hop-assemblies-client/0.20-SNAPSHOT/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mattcasters/hop-neo4j/issues/2#issuecomment-622954256>,
or unsubscribe
